FROM aperrin66/nansat:latest

RUN apt update && \
    apt install -y --no-install-recommends curl && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    ipython \
    ipdb

# RUN mkdir /usr/share/MOD44W && \
#     curl -s ftp://ftp.nersc.no/nansat/test_data/MOD44W.tgz | tar -xz -C /usr/share/MOD44W

WORKDIR /src