FROM aperrin66/nansat-base

LABEL maintainer="Anton Korosov <anton.korosov@nersc.no>"
LABEL purpose="Nansat and other geospatial Python libs"

WORKDIR /tmp
COPY utilities/ utilities/
COPY nansat/ nansat/
COPY setup.py setup.py
RUN apt update && \
    apt install -y --no-install-recommends g++ && \
    python setup.py install && \
    apt remove -y g++ && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /src
